project:
  type: book
  output-dir: _book

book:
  title: "Introducción al entorno de programacón R y su aplicación en el análisis estadístico de datos"
  author: "P. Agr. Ludwing Isaí Marroquín Jiménez"
  output-file: "MANUAL"
  date: today
  date-format: medium
  favicon: logo_cete_vector.png
  description: Este manual es una guía práctica para aprender R y RStudio, enfocándose en análisis estadístico, manipulación y visualización de datos.
  keyword: RStudio, Análisis estadístico, Reproducibilidad
  url: https://github.com/Ludwing-MJ/introduccion_R_CETE
  page-navigation: true
  sidebar: 
    logo: logo_cete_vector.png
    search: true
    collapse-level: 2

  repo-subdir: book
  sharing: [twitter, linkedin]
  downloads: [pdf, epub]
  image: logo_cete_vector.png

  page-footer:
    center: 
      - text: "Licecia"
        href: license.qmd
        
  chapters:
    - index.qmd
    - part: "Introducción a R y RStudio"
    - 01_cbasicos.qmd
    - 02_instalacion_confi.qmd
    - part: "Conceptos básicos de R"
    - 03_inicio.qmd
    - 04_datos.qmd
    - 05_importacion.qmd
    - 06_operadores.qmd
    - 06.1_funciones.qmd
    - 07_paquetes.qmd
    - part: "Manipulación de datos"
    - 08_manipulacion.qmd
    - part: "Visualización de datos"
    - 09_visualizacion.qmd
    - part: "Exportación de resultados"
    - 10_exportacion.qmd
    - part: "Material de apoyo y referencias"
    - references.qmd
    - part: "Ejemplos de Análisis Estadístico con R"
    - estadistica_descriptiva.qmd
    - regresion_simple.qmd

bibliography: references.bib
biblio-style: "apalike"

format:
  html:
    lang: es
    number-sections: true
    theme: 
      light: flatly
      dark: cyborg
    css: custom.css
    number-depth: 4
    link-external-icon: true
    link-external-newwindow: true
    
  pdf:
    lang: es
    documentclass: scrreprt
    classoption: ["onepage", "openany"]
    papersize: a4
    toc: true
    margin-top: 35mm
    margin-left: 30mm
    margin-bottom: 30mm
    margin-right: 30mm
    titlepage-geometry: 
      - top=35mm
      - bottom=30mm
      - right=30mm
      - left=30mm

  epub: 
    lang: es
    belongs-to-collection: "Introducción al entorno de programación R y su aplicación en el análisis estadístico de datos"
    group-position: 0
    creator: "P. Agr. Ludwing Isaí Marroquín Jiménez"
    rights: "© Ludwing | 2025"
    fig-responsive: true
    number-sections: true

editor: visual

